[update]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
path = "app"
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePath = "prefs/TrollVNCPrefs"
localizablePath = "."
customFunction = "LocalizedStringResource"
defaultToKeys = false
additive = true
unstripped = false

[update.normalize]
path = "prefs/TrollVNCPrefs"
sourceLocale = "zh-Hans"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "prefs/TrollVNCPrefs"
duplicateKeys = true
emptyValues = true
